### ISSUE TITLE
Include containerWidth and containerHeight in readme

### ISSUE THREAD

**Issue by louisjuliendo** [aullman/opentok-layout-js#103]
Hi @aullman, first of all I want to say thanks for this great library!

Do you think we could include `containerWidth` and `containerHeight` as part of the options in readme file?

I'm using this lib together with `opentok-react ` and I was wondering why my layout data is not updated when I call the `getLayout()` on a dynamic-sized container (I passed in default options) until I found out that there are other options: container width & height (i.e undocumented) with default value of `640px` for width and `480px` for height.

**Comment by aullman** [comment]
Ah yes, will do. Thanks!
