### ISSUE TITLE
[Question] Is it possible to implement this layout?

### ISSUE THREAD

**Issue by watch-janick** [aullman/opentok-layout-js#104]
Hello,

I'm trying to implement this layout:
<img width="609" alt="Screen Shot 2021-11-24 at 14 55 21" src="https://user-images.githubusercontent.com/11473142/143253074-3a8ed694-865a-4321-8a65-4a7ffedab7da.png">
<img width="688" alt="Screen Shot 2021-11-24 at 14 55 33" src="https://user-images.githubusercontent.com/11473142/143253095-864c893e-a186-4106-9532-d1b38db9654b.png">
<img width="593" alt="Screen Shot 2021-11-24 at 14 55 44" src="https://user-images.githubusercontent.com/11473142/143253109-4f322eca-3cb5-4a81-9a7e-629de50cd4fa.png">

I don't find a way to implement it with this library, am I missing something or it's not possible out of the box?

Do you think it would be possible to implement it and could you point me out to a place in the source code where I could implement it myself?

Thanks! 🙏

**Comment by aullman** [comment]
Yes it's totally possible to implement that layout. I'm not sure what you are missing? That looks like one big element with participants at the bottom. The tricky thing is you are changing the height of the list of participants. What is that based on? The number of participants? You could change the bigPercentage as the number of participants changes. Or maybe you just want to use the `bigPercentage` and `minBigPercentage` which will choose a size for the big area that minimises the whitespace. Something like:

```js
const layout = OT.initLayoutContainer(container, {
  bigFixedRatio: true, // Maintain the aspect ratio of the big element (not sure if you want this)
  fixedRatio: true, /// Maintain the aspect ratio of the smaller participants
  bigPercentage: 0.9,
  minBigPercentage: 0.6,
})

```

**Comment by watch-janick** [comment]
I must be missing something obvious because when I'm trying this config, the streams are added either on the right side or the left side, depending on `bigFirst` value:
<img width="1527" alt="Screen Shot 2021-11-25 at 12 58 08" src="https://user-images.githubusercontent.com/11473142/143437969-43d720d6-f688-4f43-82f1-1322c864bcb4.png">
<img width="1529" alt="Screen Shot 2021-11-25 at 12 58 19" src="https://user-images.githubusercontent.com/11473142/143437992-fb388a91-82e4-4c40-ac68-5d4057f5117b.png">
<img width="1449" alt="Screen Shot 2021-11-25 at 12 58 35" src="https://user-images.githubusercontent.com/11473142/143437998-14e65448-a404-492c-a070-77b56cc2b94e.png">
<img width="1536" alt="Screen Shot 2021-11-25 at 13 00 46" src="https://user-images.githubusercontent.com/11473142/143438148-7051609a-cfc3-41e8-9513-6ee4177b3921.png">

Here's my config:
```
const options = {
  maxRatio: 9 / 16,
  minRatio: 9 / 16,
  fixedRatio: false,
  scaleLastRow: false,
  alignItems: 'center',
  bigPercentage: 0.9,
  minBigPercentage: 0.6,
  bigFixedRatio: false,
  bigScaleLastRow: false,
  bigAlignItems: 'center',
  smallAlignItems: 'center',
  maxWidth: Infinity,
  maxHeight: Infinity,
  smallMaxWidth: Infinity,
  smallMaxHeight: Infinity,
  bigMaxWidth: Infinity,
  bigMaxHeight: Infinity,
  bigMaxRatio: 9 / 16,
  bigMinRatio: 9 / 16,
  bigFirst: false,
  animate: false,
}
```

Do you have any idea?

**Comment by watch-janick** [comment]
Hello @aullman, I'm sorry to insist.

I still haven't figured out a way to have the elements under the big one.
Would you have any idea why?

Thank you 🙏

**Comment by aullman** [comment]
It automatically decides whether to put the participants on the side or the bottom depending on the dimensions of the container. If you resize it to be narrow it will put the participants on the top or bottom. If you want to force it to always be on the bottom then you should probably not use the big feature. You can probably just use eg. flexbox layout to put the big one on top and the layout container below (without big elements) if you know what I mean.

**Comment by watch-janick** [comment]
@aullman Alright, that makes sense.

I'll play with it and see if I can find the right balance using a flexbox layout.

Thank you very much :)
