### ISSUE TITLE
Small items are right aligned

### ISSUE THREAD

**Issue by Nureckiy** [aullman/opentok-layout-js#105]
When there are big elements and small ones on the right, they are right-aligned, when it is preferable that they are close to big ones (when using wide monitors or specific aspect ratios of big screens, this looks too far). How can this be achieved?

Thank you in advance!

![image](https://user-images.githubusercontent.com/17616120/144876730-5ac3a3f2-d7c4-40a2-88b7-b458ac8e0319.png)

**Comment by aullman** [comment]
You can use the `minBigPercentage` setting to alleviate this. Right now it looks like you have `bigPercentage` set to 0.8 which results in 80% of the space being taken up by the big area.

<img width="1689" alt="image" src="https://user-images.githubusercontent.com/733672/156309341-1dcbf17f-eb8b-4529-bb4b-4a0ba02f99f4.png">

But if you set the `minBigPercentage` as well to eg. 0.5. Then it will steal some of that big space if it is not needed. But the big area will always take up at least 50% of the space. 

<img width="1691" alt="image" src="https://user-images.githubusercontent.com/733672/156309425-a33ecb9d-3926-4939-a82c-734e85b0234c.png">
