### ISSUE TITLE
Small items are smaller than they could be.

### ISSUE THREAD

**Issue by StagasaurusRex** [aullman/opentok-layout-js#113]
I am experiencing a similar issue to #105, where small videos to the right of big videos are right aligned on a wide monitor, but my issue is that the videos could be larger while maintaining the aspect ratio. Is this intended behavior?
<img width="2354" alt="Screen Shot 2022-03-01 at 11 42 35 PM" src="https://user-images.githubusercontent.com/4968936/156305041-c526981d-eefd-4855-b0ee-22e3cbf9ae00.png">
<img width="2340" alt="Screen Shot 2022-03-01 at 11 50 11 PM" src="https://user-images.githubusercontent.com/4968936/156305056-46fcd39b-aca5-4fc8-91f6-24bfbb7909a1.png">

**Comment by aullman** [comment]
Yes that is intended behaviour but you can work around it. There is a `bigPercentage` which you set which hard codes the percentage of space that the big area will take up. But there is also a `minBigPercentage`. If you set that then you can make the big area take up less space if it doesn't need to take it all up. It looks like right now you have the big percentage set to 0.8 (80%). But you probably want to set the `minBigPercentage` to something like 0.6. That will allow the small widgets to get bigger in this example and remove some of that extra space in between.

**Comment by StagasaurusRex** [comment]
Thank you for your quick reply, that works perfectly.
