### ISSUE TITLE
By removing OT_big from element, does it effect the resolution?

### ISSUE THREAD

**Issue by KittPhi** [aullman/opentok-layout-js#116]
I am using the double-click function to focus on video elements (making them larger or smaller) by adding/removing the OT_big class. In a layout where you have 4 video elements. One dominant video element (focused) while the other video elements are small thumbnails. Are all the video elements the same resolution? If so, can we improve the performance by lowering the resolution of the smaller video elements? Maybe after the OT_big has been removed?

**Comment by aullman** [comment]
Yeah, resizing the video itself will not make the publisher on the other side send you a different resolution. If you're using OpenTok then you can use the [setPreferredResolution](https://tokbox.com/developer/sdks/js/reference/Subscriber.html#setPreferredResolution) method on the Subscriber to request a different resolution from the server.
