### ISSUE TITLE
Problems with existing versions of jQuery

### ISSUE THREAD

**Issue by michplunkett** [aullman/opentok-layout-js#18]
![screen shot 2015-07-22 at 5 19 14 pm](https://cloud.githubusercontent.com/assets/5885605/8838863/d415fb4a-3095-11e5-911d-99fa1ebde5db.png)

This goes on to make all references to jQuery using the $ error out. The plug-in worked as intended when I commented out lines 289-291.

**Comment by aullman** [comment]
Thanks, I've removed that.
