### ISSUE TITLE
TokBox video not resizing on Firefox?

### ISSUE THREAD

**Issue by lgorse** [aullman/opentok-layout-js#19]
I'm setting up a browser-based subscriber stream that broadcasts a portrait (1280x720p) stream to the viewer.

i'm using Layout and it properly sizes the video container in Chrome. The container first loads as a square then adopts the correct proportions.

However in Firefox, the container first loads as a squasre, and only resizes after I resize the window. It looks like the first "layout()" call (see code below) is entirely ignored.

I've attached 2 images. One shows the initial loading appearance of the video container (it lasts about .5 seconds) then the correct appearance as it shows on Chrome afterwards.

Here is the code:
```
session.on('streamCreated', function(event){
								console.log("Successfully linked to session");
								session.subscribe(event.stream, 'publisher',{
									insertMode: 'append',
									height: '100%',
									width: '100%'
								}, function (error){
									if (error){
										console.log("an error");
									}else{
										layout();
										console.log("we're subscribed");
										var resizeTimeout;
										window.onresize = function() {
											clearTimeout(resizeTimeout);
											resizeTimeout = setTimeout(function () {
												console.log("Hello Resize");
												layout();
											}, 20);
										};
										

										
									}

								});
```

![screen shot 2015-08-07 at 12 13 12 am](https://cloud.githubusercontent.com/assets/2904000/9130605/2c226b0c-3c99-11e5-8667-373fca0562fe.png)
![screen shot 2015-08-07 at 12 13 17 am](https://cloud.githubusercontent.com/assets/2904000/9130607/2ed91616-3c99-11e5-9566-fa0a3c6cfefa.png)

**Comment by aullman** [comment]
It sounds like the subscribe completion handler might be firing too soon for Firefox. Have you tried using a similar setTimeout function for the first layout?
