### ISSUE TITLE
Resizing Subscriber Streams

### ISSUE THREAD

**Issue by lgorse** [aullman/opentok-layout-js#20]
Is it not possible to resize subscriber streams? I'm using WebRTC on a browser so viewers can consume a live stream that comes from a mobile app. So the viewers on browser are exclusively subscribers, they don't publish (for now). 

Once I define the layout in my CSS, however, the subscriber container never changes size. Is this an implementation problem or a decision on your part not to handle subscriber stream resizing?

```
#tokbox_layout{
	margin: auto;
	position: relative;
	height: 427px;
	width: 240px;

}
```

And the layout() javascript call:
```
var layoutContainer = $("#tokbox_layout").get(0);
	var layout = initLayoutContainer(layoutContainer,{
		fixedRatio: true,
		bigFixedRatio: true
	}).layout;
```

**Comment by aullman** [comment]
Subscriber stream resizing should definitely work. I'm not sure why it's not working for you. Are you saying that the Publisher works but not the Subscriber? I'm confused because in #19 you are claiming it works just not in Firefox.

**Comment by lgorse** [comment]
Yes it works and I forgot to close this issue.
The issue does remain in Firefox.
