### ISSUE TITLE
Remove console messages

### ISSUE THREAD

**Issue by bunbutter** [aullman/opentok-layout-js#25]
opentok-layout.js prints console message. it would be good to get rid of those

**Comment by aullman** [comment]
Done, thanks.

**Comment by bunbutter** [comment]
Thanks. How about a new release?

**Comment by aullman** [comment]
https://github.com/aullman/opentok-layout-js/releases/tag/v0.4.1

**Comment by bunbutter** [comment]
You have not released a version of 0.4.*, how do I pull 0.4.1 ?

**Comment by aullman** [comment]
Both `npm install` and `bower install` are working for me. How do you normally get it?

**Comment by bunbutter** [comment]
bower install. I usually specify ~<major-release>.<minor-release>.<tag-release>, for opentok since you have 0.1.4 as the latest release, I have ~0.1.4 in my bower json file.

**Comment by aullman** [comment]
Change that to ~0.4.1
