### ISSUE TITLE
At some screen sizes 'OT_big' is smaller than regular elements

### ISSUE THREAD

**Issue by rhclayto** [aullman/opentok-layout-js#28]
Hi,

Basically what the title says. Specifically, as the screen width moves into smartphone-size range, elements with the 'OT_big' class get smaller while elements without the class get larger, until at a certain point the 'OT_big' elements actually get smaller than the unadorned elements. This is unexpected behavior, & makes using the class on responsive layout for large screens & mobile devices have opposite effects in those two contexts.

Any ideas on how to fix or work around this?

Thanks for your great work!

**Comment by aullman** [comment]
Are you using a fixed ratio for the large elements and not a fixed one for the small ones?

**Comment by aullman** [comment]
If you set bigFixedRatio to false it should let you make it bigger because it's not trying to stick within the ratio. Or if you make both fixedRatio:true and bigFixedRatio:true.

**Comment by rhclayto** [comment]
This is happening for me with the demo as well in Chrome & Firefox. I will try your suggestions & see how it goes. However, I've gone in another direction so this isn't a really big problem for me now. (I'm using opentok-layout-js but with one ot element nested inside another to get a picture-in-picture effect.)  Thanks for your help.
