### ISSUE TITLE
Best way to rearrange publishers and subscribers on demand

### ISSUE THREAD

**Issue by deardooley** [aullman/opentok-layout-js#29]
I'd like to use the opentok-layout-js app to rearrange the user displays on demand. Layouts I'd like to provide are:  
* picture in picture (floating)  
* grid  
* split screen horizontally  
* split screen vertically  
* horizontal cover flow (google hangout style)  
* vertical cover flow (google hangout style with vertical participant windows on right side)  

Can you point me in the right direction on how to accomplish this efficiently using this library? I'm proofing it out within the opentok-meet app at the moment.

**Comment by aullman** [comment]
@deardooley this library is designed to just do grid layout and split screen but it automatically detects whether horizonal or vertical makes more sense depending on which will have the least blank space.

For implementing these other layouts I would probably start with a different library with different requirements.
