### ISSUE TITLE
Breaking other libraries with exports object

### ISSUE THREAD

**Issue by simonasdev** [aullman/opentok-layout-js#30]
Initial lines of this library define a global `exports` property on `window`:
```javascript
if (typeof module === 'undefined' || typeof module.exports === 'undefined') {
  exports = window;
} else {
  var window = null;
}
```
This results in breaking all other libraries that are loaded in the same webpage that does checks for Node environment by the use of exports object: `typeof exports === 'object'`. Therefore I think that modifying window by adding exports object to it is a bad idea and should be fixed and released as fast as possible. 

One solution would be to wrap everything in self invoking function and define local variables, instead of global ones, since this exports object isn't used anywhere other than defining `initLayoutContainer` on it, and in turn on window.
How would you like it handled?

**Comment by aullman** [comment]
Good point, global exports is nasty. How about changing it to something like:

```javascript
var initLayoutContainer = 
/// ...
if (typeof module === 'undefined' || typeof module.exports === 'undefined') {
  window.initLayoutContainer = initLayoutContainer;
} else {
  module.exports.initLayoutContainer = initLayoutContainer;
}
```

**Comment by xeroxoid** [comment]
Damn, I was trying to find out which of the 30+ libs we use is setting a global variable ```exports``` .

**Comment by LoganLehman** [comment]
Will https://github.com/aullman/OpenTok-Angular be updated to use the most recent version? I can't change the dependency version it relies on in bower as far as I know. @aullman

**Comment by aullman** [comment]
@LoganLehman I just pushed an update.

@xeroxoid sorry for the hassle!
