### ISSUE TITLE
Layout not loading consistently

### ISSUE THREAD

**Issue by mistaguy** [aullman/opentok-layout-js#32]
When more that 2 persons are in a call and then one of the users reloads the entire page, sometimes other users views on other screens also disappear. see [https://www.screenmailer.com/v/x2xhwM4I3Sa2aTo](Screeen)

**Comment by aullman** [comment]
I'm not sure exactly what is happening here. Could you talk me through steps to reproduce this problem? Perhaps also link me to your app or some sample code that displays the issue.

**Comment by maxbenz** [comment]
Hi Adam,

I am the product lead at mpowr (and the second person in the screencast). 

The app can be found here: https://mpowr.io. You'll need to sign up via Slack to test it as a host. Alternatively, you can attend my room without signing up here: https://mpowr.io/Max_Benz1

Let me know if you have some time. I would be glad to explain the issue and to reproduce the problem with you.
