### ISSUE TITLE
Video element turns very small when a participant leaves

### ISSUE THREAD

**Issue by utkarsha2016** [aullman/opentok-layout-js#35]
When layout() is called on event streamDestroyed the video element turn into a tiny square

**Comment by aullman** [comment]
Can you link me to an example and give me steps to repro?

**Comment by utkarsha2016** [comment]
I am not how to share my entire code here, but I can share privately with you. I am using the latest Angular and calling layout each time a new stream is added(which works fine and re arranges it nicely) but when a stream is destroyed and the layout function is called the element width and height becomes 0. One thing that is different from the example is I don't call layout when my own publisher is initialized and neither have I included the publisher div in the layout container. The application I am trying to make is video conferencing and the person's own video is always small on top right corner.
