### ISSUE TITLE
Top align elements

### ISSUE THREAD

**Issue by slpn1** [aullman/opentok-layout-js#36]
Hi. Love this, thanks. Would it be an easy change to top align elements in their container. At the moment they are vertically middle aligned which makes it hard for me to line things up as per design. Thanks!

**Comment by aullman** [comment]
This would be quite an easy change actually. There is a section in the code with the comment "vertical centering" where it sets `y = ((containerHeight - (totalRowHeight)) / 2);`. You would just have to set that to 0. I welcome a PR if you want to make this change. It could be an extra option, eg. `verticalAlign:'top'|'middle'|'bottom'` which defaults to 'middle'.
