### ISSUE TITLE
Example without OpenTok

### ISSUE THREAD

**Issue by drale2k** [aullman/opentok-layout-js#53]
Is there an example on how to use it without OpenTok? Especially which HTML layout does the library expect in order to work properly. I see it mentioned in the README that it is supposed to work without OpenTok but all the code references seem to be expecting OpenTok

**Comment by aullman** [comment]
Yeah it should work with any elements. If you just put a bunch of video or image elements inside the container and call `layout()` then it will work. Do you have any specific issues?
