### ISSUE TITLE
Fixed ratio for only one video

### ISSUE THREAD

**Issue by saschametz** [aullman/opentok-layout-js#57]
Is it possible to keep the aspect ratio for only one element (fixedRatio: true) but not for the others (fixedRatio: false)?

This would be helpful if someone adds a screen to share with others to show a presentation which shouldn't be cropped. (Maybe a "fixedRatio" class)

**Comment by aullman** [comment]
Yeah good call. For now the way I have been doing this use-case is to make the screen big by giving it the "OT_big" class then set the `bigFixedRatio` to true.
