### ISSUE TITLE
fixed layout

### ISSUE THREAD

**Issue by haricet** [aullman/opentok-layout-js#58]
Hi i am new to tokbox. how  to setup fixed  one big and rest all small, onclick replace the big with clicked small element and the make the big one is small .  I tried to achive the same,but unable to get it done. Please guide me on this. thanks for your wonderful work.

**Comment by aullman** [comment]
You should be able to do this just by changing classes. So give the big element an "OT_big" class. Then when you click an element make that one "OT_big" and remove "OT_big" from the others. I'm doing something similar in the demo with double click [here](https://github.com/aullman/opentok-layout-js/blob/master/index.html#L172)
