### ISSUE TITLE
Add support for use with Cordova

### ISSUE THREAD

**Issue by mark-veenstra** [aullman/opentok-layout-js#6]
We have tried to get opentok-layout compatible with Apache Cordova and the use of https://github.com/songz/cordova-plugin-opentok. We successfully made some changes to get this implemented.

What we did:
* OT.$ variable doesn't exist when using Cordova. We wrapped an if statement around all the places where OT.$ variable is used and replaced it with OT.OTHelper.
* Cordova plug-in is not getting updated (with the OT.updateViews function). So we added an updateViews function to the function positionElement.

See adjusted file on pastebin: http://pastebin.com/vjF5g5sf

**Comment by aullman** [comment]
You just need to make sure you define OT.$ using https://github.com/aullman/opentok-meet/blob/master/opentok-meet-cordova/www/mobile.js#L15
