### ISSUE TITLE
stack small items below

### ISSUE THREAD

**Issue by ross-ewing** [aullman/opentok-layout-js#62]
Hi, be a good feature to add that if bigPercentage = 1 then the small videos align below by default and don't stack on the right. Im not sure if i'm just missing this in the advance settings to force this functionality to work, if i am let me know otherwise i will try and arrange a pr for this feature. 

Thanks

**Comment by aullman** [comment]
Right now it tries to intelligently decide whether to put the small elements on the right or below depending on the size of the container. If the window is wider than it is tall then the small videos will be on the right. 

![image](https://user-images.githubusercontent.com/733672/104390344-926a7000-5591-11eb-90bb-696425e87134.png)


If the window is taller than it is wide then it will put them at the bottom. 

![image](https://user-images.githubusercontent.com/733672/104390386-b0d06b80-5591-11eb-8348-27d55e3a01c9.png)


If you want to force it to always be on the right or always on the bottom I would add a new property. Something like `bigPosition: 'top' | 'bottom' | 'left' | 'right' | 'auto'`
