### ISSUE TITLE
How do i implement in angular 8 ?

### ISSUE THREAD

**Issue by dVp007** [aullman/opentok-layout-js#66]
Can you help me how to implement this in my app which is build on angular .
Thanks

**Comment by aullman** [comment]
I don't have any sample code for Angular 8 but I do have some for Angular 1 [here](https://github.com/aullman/OpenTok-Angular/blob/master/opentok-angular.js#L91) where I'm creating a directive.

The same concept should apply where you can create an Angular component or directive that uses this layout class.
