### ISSUE TITLE
Incorrect check for jquery, and no mention of jquery dependency in the doc

### ISSUE THREAD

**Issue by maikthomas** [aullman/opentok-layout-js#67]
Correct me I'm off track here, but it seems that this uses JQuery for animations, however I see no reference made to JQuery in the readme.
There's also a check:
`if (animate && $) {`
https://github.com/aullman/opentok-layout-js/blob/master/src/layout.js#L65
but if $ is not defined this throws:
`ReferenceError: $ is not defined`

**Comment by aullman** [comment]
Yeah, it can use jQuery for animations but you can also just use CSS animations (which I would recommend). There are some instructions on using CSS animations [here](https://github.com/aullman/opentok-layout-js#animations).

But you're right, if you try to animate and you don't have jQuery then you will get an error. But if you don't have jQuery then animating won't work anyway.

**Comment by maikthomas** [comment]
Ok I think I understand: the animate option flag is to animate using jquery, so if you don't have it, it fails.
You can animate using CSS and the animate option set to false.
This could probably be explained in the readme. Do you want me to do a PR with readme changes?
