### ISSUE TITLE
How do we add a an option like "OT_big" on an other class other than subscribers and publishers?

### ISSUE THREAD

**Issue by meljason** [aullman/opentok-layout-js#76]
So I am using the layout library to automatically resize the caller's window. I added the option of maxWidth: Infinity to both the subscribers and the publishers. However, I am adding another element to the main call div, that is, subscribers, publisher, customElement and I want the customElement to get the option of "OT_big" to make the customElement bigger than the other elements. But the issue is, I tried to add the attribute of class="OT_big" to the customElement in my html but the effect does not apply when customElement joins the call. I

https://user-images.githubusercontent.com/34180725/104326984-531c2080-54b8-11eb-85d6-4d3845cb6844.mp4

 have to resize my window for it to apply for some reasons. Is there any way to fix it?

**Comment by aullman** [comment]
Yeah, you should just need to call layout again after you add the OT_big class. What's probably happening is you're calling layout again when resizing so it's getting fixed them.

**Comment by meljason** [comment]
Thank you! I does work now. Great job!
