### ISSUE TITLE
resize technique breaks zoom/crop with opentok.js v2.4.0

### ISSUE THREAD

**Issue by aoberoi** [aullman/opentok-layout-js#8]
since the 2.4.0 update, the layout container's resizing of elements improperly impacts the crop/zoom behavior of publishers/subscribers. examples using the demo page in this repo:

1 publisher (doesn't capture full frame and black bar on right):
![screen shot 2015-01-17 at 2 49 31 pm](https://cloud.githubusercontent.com/assets/494795/5790524/c143562e-9e6a-11e4-9751-7aac70e168b3.png)

2 publishers (black bars on bottom):
![screen shot 2015-01-17 at 2 49 41 pm](https://cloud.githubusercontent.com/assets/494795/5790525/cbf59078-9e6a-11e4-8266-7bfbec5feddc.png)

3 publishers (black bars on bottom - all different):
![screen shot 2015-01-17 at 2 49 48 pm](https://cloud.githubusercontent.com/assets/494795/5790526/d77bbf3a-9e6a-11e4-9032-c6c2d8ab432c.png)

middle publisher made big (really weird cropping):
![screen shot 2015-01-17 at 2 49 53 pm](https://cloud.githubusercontent.com/assets/494795/5790527/e3053570-9e6a-11e4-9081-f35f881b2882.png)

sorry about the killer stare face :smile:

**Comment by aullman** [comment]
This looks like it's not an issue anymore from my testing. I think this was actually a bug in opentok 2.4 which we fixed.
